
server:
  address: "127.0.0.1"
  port: 1090
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

logging:
  pattern:
    file: "[%d{yyyy-MM-dd HH:mm:ss}][%p][%file : %line] %m%n"
    console: "[%d{yyyy-MM-dd HH:mm:ss}][%p] %m%n"
  file.name: "./log/api.log"

springdoc:
  swagger-ui:
    enabled: true
  api-docs:
    enabled: true

management:
  endpoints:
    web:
      base-path: "/actuator"
      exposure:
        include: "*"
  endpoint:
    shutdown:
      enabled: true

xtquant:
  order-queue: 'xtquant-order-list'
  # feed parsing interval in milliseconds
  output-parsing-interval: 50
  output-dir: 'E:\\GjQMT\\output'
  # 输出文件是否包含 finish 标识文件, 当为 true 时，数据解析完成后，会自动删除 finish 标识文件 以及 对应的数据文件
  output-finish-flag: false
